services:
  postgres:
    image: postgres:latest
    container_name: hotel_postgres
    restart: always
    environment:
      POSTGRES_DB: hotel_db
      POSTGRES_USER: aritr
      POSTGRES_PASSWORD: hotel_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: hman
    depends_on:
        - postgres
    ports:
        - "8080:8080"

volumes:
  postgres_data:
