services:
  postgres:
    image: postgres:latest
    container_name: hotel_postgres
    restart: always
    environment:
      POSTGRES_DB: hotel_db
      POSTGRES_USER: aritr
      POSTGRES_PASSWORD: hotel_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
